version: '2'

services:

  app:
    image: node:latest
    container_name: app
    restart: unless-stopped
    depends_on:
      - "db"
    volumes:
      - ./server:/var/www/backend
    networks:
      vps-ikram-network-lan:
        ipv4_address: 192.168.20.10
    command: bash -c "cd /var/www/backend && npm i argon2 && npm i && npm run dev:production"
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      vps-ikram-network-lan:
        ipv4_address: 192.168.20.11
    volumes:
      - ./database/data:/var/lib/postgresql/data
networks:
  vps-ikram-network-lan:
    name: vps-ikram-network-lan
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1