name: Deploiement with test
on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./.github/workflows/test.yml

  deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls
            cd TFE-2022-2023
            git pull origin develop
            git status
            cd client && npm i 
            cd ../server && npm i
            rm -rf build 
            cd ../client && npm run build && mv build/ ../server
            cd .. && docker-compose up -d 
