
name: Deploiement with test
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy and test
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls
            cd TFE-2022-2023
            git pull origin develop
            git status
            cd server && npm install
            # lancé les tests de mocha
            mocha
            # Si mocha passe on lance le script de déploiement
            if [ $? -eq 0 ]; then
              cd rm -rf build
              cd ..client && npm run build
              mv build/ ../server
              cd .. && docker-compose up -d
            else 
              echo "Les tests ont échoués"
            fi
