name: Deploiment
on:
  push:
    branches:
      - develop

jobs:
  unit-tests-frontend :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
        
  unit-tests-backend :
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

  VPS-deploiement:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build application
        working-directory: .
        run: |
          cd client 
          npm install --force
          CI= npm run build

      - name: Application folder to remote
        uses: appleboy/scp-action@master
        with:
          source: Application/
          target: /home/geoffreyb/TFE-2022-2023/Application
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATEKEY }}

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATEKEY }}
          script: |
            cp .env /home/geoffreyb/TFE-2022-2023/Application/www/backend
            cp .env /home/geoffreyb/TFE-2022-2023/Application
            cd /home/geoffreyb/TFE-2022-2023/Application
            docker-compose down
            docker-compose up -d
