# This is a basic workflow to help you get started with Actions

name: Deployement

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATEKEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd ~/home/geoffreyb/TFE-2022-2023
          git pull origin develop
          git status
          cd /client && npm i 
          cd ../server && npm i
          rm -rf build 
          cd ../client && npm run build && mv build/ ../server
          cd .. && docker-compose up
