name: remote ssh command
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check if test succeeded
        id: test_status
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file_name: '.github/workflows/integration_unit_test.yml',
              status: 'success',
              branch: context.ref
            });
            console.log(data.total_count);
            if (data.total_count === 0) {
              process.exit(1);
            }

      - name: executing remote ssh commands using password
        if: steps.test_status.outputs.result == 'true'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls
            cd TFE-2022-2023
            git pull origin develop
            git status
            cd client && npm i 
            cd ../server && npm i
            rm -rf build 
            cd ../client && npm run build && mv build/ ../server
            cd .. && docker-compose up -d
