name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i --force
        working-directory: client

      - name: Build client
        run: 
          # disabled eslint for build
          eslint --ignore-path .gitignore --ext .js,.jsx,.ts,.tsx --no-error-on-unmatched-patter
          npm run build

        working-directory: client

      - name: Remove previous build
        run: |
          ssh ${{secrets.VPS_USER}}@${{secrets.VPS_HOST}} 'rm -rf server/build'

      - name: Move build to server
        run: |
          scp -r client/build ${{secrets.VPS_USER}}@${{secrets.VPS_HOST}}:server

      - name: SSH into VPS and run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VPS_HoST}}
          username: ${{secrets.VPS_USER}}
          key: ${{ secrets.VPS_PRIVATEKEY }}
          script: |
            cd /server
            docker-compose up -d
            
