name: Deploiement
on:
  workflow_run:
    workflows: ["Integration and Unit tests"]
    types:
      - completed

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls
            cd TFE-2022-2023
            git pull origin develop
            git status
            cd client && npm i 
            cd ../server && npm i
            rm -rf build 
            cd ../client && npm run build && mv build/ ../server
            cd .. && docker-compose up -d 
