name: Deploiement with test
on:
  push:
    branches:
      - develop

jobs:

# 2 jobs, one who test and other who deploy. The deploy jobs need the test job
# to be finished before starting
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo "Test"
          sleep 10
          echo "Test done"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploy"
          sleep 10
          echo "Deploy done"
