name: Deploiement with test
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy and test
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls
            cd TFE-2022-2023
            git pull origin develop
            git status
            cd server && npm install
            mocha 
            
            # Vérifier si les tests ont réussi
            if [ $? -eq 0 ]; then
              cd ../client && npm install
              npm run build # Étape de construction du build
              cd ../server && rm -rf build
              mv build/ ../server

              cd .. && docker-compose up -d # Étape de mise en ligne avec Docker
            else
              echo "Tests failed. Skipping build and deployment."
            fi
