name: Deploiement with test
on:
  push:
    branches:
      - develop

jobs:

# 2 jobs, one who test and other who deploy. The deploy jobs need the test job
# to be finished before starting
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          script : |
            cd TFE-2022-2023
            git pull
            cd server
            mocha --exit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploy"
          sleep 10
          echo "Deploy done"
