name: Uptime Check
on:
  schedule:
    - cron: '0 * * * *'  # Exécuter toutes les heures

jobs:
  uptime-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run uptime check
        uses: some-username/uptime-checker-action@v1
        with:
          url: https://jeanvives.be
          timeout: 10s
          success_threshold: 95
